"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['QuickCut.py']
DATA_FILES = []
OPTIONS = {
 'excludes': 'pkg_resources.py2_warn,Tkinter',
 'iconfile': './icon.icns',
 'optimize': True,
 'packages': 'srt,keyboard,numpy,setuptools,aliyunsdkcore,PyQt5,audiotsm,scipy,qcloud_cos,tencentcloud,oss2,pyaudio,Crypto,auditok,image,pymediainfo',
 'plist': './info.plist',
 'qt_plugins':True,
 'report_missing_from_imports': True,
 'use_faulthandler': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
