"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['QuickCut.py']
DATA_FILES = []#move MacRely to QuickCut.app/Contents/Resourses
OPTIONS = {'iconfile': '/Users/leavelet/Desktop/QuickCut/icon.icns','packages': ["srt","keyboard","numpy","setuptools","aliyunsdkcore","PyQt5","audiotsm","scipy","qcloud_cos", "tencentcloud","oss2","pyaudio","Crypto"
], 'excludes': ["pkg_resources.py2_warn","Tkinter"],}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
